name: Satellite Release on Tags

on:
  push:
    tags:
      - '**'

jobs:
  release-module:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v3'
        with:
          ref: ${{ github.ref }}
          persist-credentials: false
      - name: Create Release
        run: gh release create ${{ github.ref }} --generate-notes
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Generate SBOM (CycloneDX)
        uses: aquasecurity/trivy-action@0.30.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: cyclonedx
          output: sbom.cdx.json
      - name: Get tag name
        id: extract_tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_REF: ${{ github.ref }}
      - name: Attach SBOM to release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${{ steps.extract_tag.outputs.TAG_NAME }}" sbom.cdx.json --clobber
