name: Satellite Release on Tags

on:
  push:
    tags:
      - '**'

jobs:
  release-module:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v4'
      - name: Create Release
        run: |
          gh release view ${{ github.ref_name }} >& /dev/null || \
          gh release create ${{ github.ref }} --title ${{ github.ref_name }}  --generate-notes
        env:
          GH_TOKEN: ${{ github.token }}
